typography_spectrum: 0.49502955307252705
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.44219064502976835
  lightness: 0.7217975491657853
  saturation: 0.9322283661458641
  rhythmicContrast: 0.13345157471485436
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4725071960128844
analytics:
  google: null
  facebook: null
  twitter: null
name: The Book of Adhan
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Welcome to my humble abode
purpose: []
